pim_enrich_api_connection_index:
    path: ''

pim_enrich_api_connection_rest_create:
    path: /rest
    defaults: { _controller: pim_enrich.controller.rest.api_client:createAction }
    methods: [POST]
