extensions:
    pim-api-connection-index:
        module: pim/form/common/index/index
        config:
            title: pim_enrich.index.api_connection.title

    pim-api-connection-index-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: pim-api-connection-index
        targetZone: breadcrumbs
        config:
            tab: pim-menu-system
            item: pim-menu-system-api-connection

    pim-api-connection-index-grid:
        module: pim/form/common/index/grid
        parent: pim-api-connection-index
        position: 1000
        targetZone: content
        config:
            alias: api-connection-grid
