extensions:
    pim-grid-category-tree:
        module: pim/grid/category-tree/tree

    # The catalog selector
    pim-grid-category-tree-select-catalog:
        module: pim/grid/category-tree/select-catalog
        parent: pim-grid-category-tree
        targetZone: header

    # The folder list tree
    pim-grid-category-tree-list:
        module: pim/grid/category-tree/list
        parent: pim-grid-category-tree
        targetZone: content

    # The switch to include sub-categories
    pim-grid-category-tree-switch:
        module: pim/grid/category-tree/switch
        parent: pim-grid-category-tree
        targetZone: footer